header:
  version: 14

repos:
  meta-security:
    # requires some layers from meta-openembedded
    url: https://git.yoctoproject.org/meta-security
    commit: 1a3e42cedbd94ca73be45800d0e902fec35d0f0f
    branch: kirkstone
